// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8BD1IkPKR-4_8B2Da2Lu1A4eA8o4IjE',
    appId: '1:314872587586:web:00d65463fef203835e14db',
    messagingSenderId: '314872587586',
    projectId: 'whatsapp-2-9fa03',
    authDomain: 'whatsapp-2-9fa03.firebaseapp.com',
    storageBucket: 'whatsapp-2-9fa03.firebasestorage.app',
    measurementId: 'G-2RHNRTS308',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUMHRFN2Hu8DYf60SfRaRMtvODVth70Ag',
    appId: '1:314872587586:android:b5eb93ba8d86e5485e14db',
    messagingSenderId: '314872587586',
    projectId: 'whatsapp-2-9fa03',
    storageBucket: 'whatsapp-2-9fa03.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTKDnmXAKemGk6ImIxsfGOEPcfAeU8Fxw',
    appId: '1:314872587586:ios:c7bb8c54274e0f995e14db',
    messagingSenderId: '314872587586',
    projectId: 'whatsapp-2-9fa03',
    storageBucket: 'whatsapp-2-9fa03.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTKDnmXAKemGk6ImIxsfGOEPcfAeU8Fxw',
    appId: '1:314872587586:ios:c7bb8c54274e0f995e14db',
    messagingSenderId: '314872587586',
    projectId: 'whatsapp-2-9fa03',
    storageBucket: 'whatsapp-2-9fa03.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz8BD1IkPKR-4_8B2Da2Lu1A4eA8o4IjE',
    appId: '1:314872587586:web:827dc4b397149f4b5e14db',
    messagingSenderId: '314872587586',
    projectId: 'whatsapp-2-9fa03',
    authDomain: 'whatsapp-2-9fa03.firebaseapp.com',
    storageBucket: 'whatsapp-2-9fa03.firebasestorage.app',
    measurementId: 'G-CVKN23Y2YL',
  );
}
